import 'package:flutter/material.dart';
import '../dashboard_data.dart';
import '../widgets/shared_widgets.dart';

Widget _detail(Map<String, dynamic> details, String userName, int activeIndex) => AppShell(userName: userName, activeIndex: activeIndex, body: Column(children: [DetailHeader(title: details['title'] as String, userName: userName), Expanded(child: SingleChildScrollView(child: Column(children: [Text(details['subtitle'] as String), DetailTable(columns: (details['columns'] as List<dynamic>).cast<String>(), rows: details['rows'] as List<dynamic>)])))]));
class LinenDetailPage extends StatelessWidget { const LinenDetailPage({super.key, required this.type, required this.userName}); final int type; final String userName; @override Widget build(BuildContext context) => _detail((dashboardData['linenDetails'] as List<dynamic>)[type] as Map<String, dynamic>, userName, 0); }
class CategoryDetailPage extends StatelessWidget { const CategoryDetailPage({super.key, required this.type, required this.userName}); final int type; final String userName; @override Widget build(BuildContext context) => _detail((dashboardData['categoryDetails'] as List<dynamic>)[type] as Map<String, dynamic>, userName, 4); }
class TransactionDetailPage extends StatelessWidget { const TransactionDetailPage({super.key, required this.type, required this.userName}); final int type; final String userName; @override Widget build(BuildContext context) => _detail((dashboardData['transactionDetails'] as List<dynamic>)[type] as Map<String, dynamic>, userName, type == 0 ? 1 : 3); }
class RequestPage extends StatelessWidget { const RequestPage({super.key, required this.userName}); final String userName; @override Widget build(BuildContext context) => AppShell(userName: userName, activeIndex: -1, body: const Center(child: Text('PERMINTAAN LINEN & TIRAI'))); }
class QRCheckPage extends StatelessWidget { const QRCheckPage({super.key, required this.userName}); final String userName; @override Widget build(BuildContext context) => AppShell(userName: userName, activeIndex: 2, body: Column(children: [AppBar(title: const Text('QR Code Check')), const Expanded(child: Center(child: Text('Tidak ada data ditemukan')))])); }
